# Generated by Django 5.0.7 on 2024-07-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryId', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('alpha2Code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('alpha3Code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('countryName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('numericCode', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'country',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
            ],
            options={
                'db_table': 'manager',
                'ordering': ('-createTime',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'type',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VerificationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'verification',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('locale', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('managerId', models.ForeignKey(db_column='manager_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_manager', to='fetcher.manager')),
            ],
            options={
                'db_table': 'resources',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=150)),
                ('lastName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('middleName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('birthday', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17)),
                ('internalType', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('locale', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('riskLevel', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('clientId', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('loggedAt', models.DateTimeField(auto_now=True, verbose_name='Logged At')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('countryId', models.ForeignKey(db_column='country_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_country', to='fetcher.country')),
                ('type', models.ForeignKey(db_column='country_type', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to='fetcher.type')),
                ('verificationLevel', models.ForeignKey(db_column='verify_level_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_verify_level', to='fetcher.verificationlevel')),
            ],
            options={
                'db_table': 'users',
                'ordering': ('-createTime',),
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('userId', models.ForeignKey(db_column='user_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_user', to='fetcher.users')),
            ],
            options={
                'db_table': 'tags',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='manager',
            name='userId',
            field=models.ForeignKey(db_column='user_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_user', to='fetcher.users'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('shortName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('userID', models.ForeignKey(db_column='user_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to='fetcher.users')),
            ],
            options={
                'db_table': 'company',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('userID', models.ForeignKey(db_column='user_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_user', to='fetcher.users')),
            ],
            options={
                'db_table': 'analytics',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('accountNo', models.PositiveIntegerField()),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('userID', models.ForeignKey(db_column='user_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_user', to='fetcher.users')),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ('-createTime',),
            },
        ),
    ]
