# Generated by Django 5.0.7 on 2024-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
