# Generated by Django 5.0.7 on 2024-07-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0002_alter_manager_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='accountNo',
            new_name='accountNumber',
        ),
    ]
